import QtQuick
import Quickshell
import Quickshell.Io
import Quickshell.Wayland

import "./Widgets/clock"
import "./controlCenter"
import "./Widgets/notifications"
import "./Widgets/launcher"
import "./Widgets/mode"
import "./core"
import "./Widgets/wallpaper"
import "./Widgets/askpass"

ShellRoot {
  id: root

  property bool isControlCenterOpen: false

  NotificationService {
    id: notifService
  }

  PanelWindow {
    anchors { top: true; left: true; right: true }
    implicitHeight: clockItem.height + 20
    color: "transparent"

    // Fixed exclusive zone — notification banner makes the window taller
    // but keeps the clock's reservation so it floats over apps, not pushes them.
    WlrLayershell.exclusiveZone: 56
    // Exclusive keyboard grab when the askpass dialog is open — enables the
    // password field to receive keystrokes without requiring a click first.
    WlrLayershell.keyboardFocus: clockItem.showAskpass ? WlrKeyboardFocus.Exclusive : WlrKeyboardFocus.None

    MouseArea {
      anchors.fill: parent
      enabled: clockItem.showPowerMenu || clockItem.showWallpaperMenu
      onClicked: {
        clockItem.showPowerMenu = false;
        clockItem.showWallpaperMenu = false;
      }
    }

    Clock {
      id: clockItem
      anchors.horizontalCenter: parent.horizontalCenter
      anchors.top: parent.top
      anchors.topMargin: 10

      opacity: !isControlCenterOpen ? 1 : 0
      visible: opacity > 0

      Behavior on opacity {
        NumberAnimation { duration: 250; easing.type: Easing.InOutQuad }
      }

      latestNotification: notifService.latestNotification
      latestNotificationData: notifService.latestNotificationData
      storedNotifications: notifService.storedNotifications
      onNotifDismissed: (notifRef) => notifService.dismissBanner(notifRef)
      onNotifBannerDismissed: (notifRef) => notifService.dismissBanner(notifRef)

      onToggleControlCenter: isControlCenterOpen = true

      wallpaperSvc: wallpaperSvc
      modeSvc: modeSvc
      askpassSvc: askpassSvc
    }
  }

  Process {
    id: ipcChecker
    running: true
    command: ["sh", "-c",
      "while true; do " +
      "  out=''; " +
      "  test -f /tmp/qs-power-menu && rm /tmp/qs-power-menu && out=\"${out}p\"; " +
      "  test -f /tmp/qs-app-launcher && rm /tmp/qs-app-launcher && out=\"${out}a\"; " +
      "  test -f /tmp/qs-wallpaper && rm /tmp/qs-wallpaper && out=\"${out}w\"; " +
      "  test -f /tmp/qs-mode-cycle && rm /tmp/qs-mode-cycle && out=\"${out}m\"; " +
      "  test -f /tmp/qs-toggle-cc && rm /tmp/qs-toggle-cc && out=\"${out}c\"; " +
      "  if [ -n \"$out\" ]; then echo \"$out\"; fi; " +
      "  sleep 0.05; " +
      "done"
    ]
    stdout: SplitParser {
      onRead: (data) => {
        var flags = data.trim()
        if (flags.indexOf("p") >= 0 && !clockItem.showAppLauncher)
          clockItem.showPowerMenu = true
        if (flags.indexOf("a") >= 0 && !clockItem.showPowerMenu)
          clockItem.showAppLauncher = true
        if (flags.indexOf("w") >= 0)
          clockItem.showWallpaperMenu = !clockItem.showWallpaperMenu
        if (flags.indexOf("m") >= 0) {
          modeSvc.cycleMode();
          clockItem.showModeIndicator();
        }
        if (flags.indexOf("c") >= 0)
          isControlCenterOpen = !isControlCenterOpen;
      }
    }
  }
  PanelWindow {
    anchors { top: true; left: true; right: true }
    implicitHeight: clockItem.showAppLauncher ? 270 : 0
    color: "transparent"
    visible: clockItem.showAppLauncher
    WlrLayershell.layer: WlrLayer.Overlay
    WlrLayershell.exclusiveZone: -1
    WlrLayershell.focusable: true

    MouseArea {
      anchors.fill: parent
      onClicked: clockItem.showAppLauncher = false
    }

    Item {
      width: 480; height: 240
      anchors.horizontalCenter: parent.horizontalCenter
      anchors.top: parent.top
      anchors.topMargin: 10

      AppLauncher {
        id: appLauncherOverlay
        anchors.fill: parent
        radius: 28
        appService: appLauncherSvc
        onCloseRequested: clockItem.showAppLauncher = false
        onHoveredChanged: clockItem.appLauncherHovered = hovered
      }
    }
  }

  // Watch colors.json generated by matugen → push new values into Theme singleton
  FileView {
    id: themeFileWatcher
    path: Quickshell.shellPath("core/colors.json")
    watchChanges: true
    onLoaded: applyColors()
    onTextChanged: applyColors()

    function applyColors() {
      var t = text().trim()
      if (t.length < 10) return
      try {
        var c = JSON.parse(t)
        if (c.background) Theme.background = c.background
        if (c.surface) Theme.surface = c.surface
        if (c.surfaceBright) Theme.surfaceBright = c.surfaceBright
        if (c.surfaceDim) Theme.surfaceDim = c.surfaceDim
        if (c.surfaceContainer) Theme.surfaceContainer = c.surfaceContainer
        if (c.surfaceVariant) Theme.surfaceVariant = c.surfaceVariant
        if (c.primary) Theme.primary = c.primary
        if (c.primaryFg) Theme.primaryFg = c.primaryFg
        if (c.secondary) Theme.secondary = c.secondary
        if (c.tertiary) Theme.tertiary = c.tertiary
        if (c.backgroundFg) Theme.backgroundFg = c.backgroundFg
        if (c.surfaceFg) Theme.surfaceFg = c.surfaceFg
        if (c.surfaceVariantFg) Theme.surfaceVariantFg = c.surfaceVariantFg
        if (c.outline) Theme.outline = c.outline
        if (c.outlineVariant) Theme.outlineVariant = c.outlineVariant
        if (c.error) Theme.error = c.error
      } catch (e) {
        console.error("theme colors parse error:", e)
      }
    }
  }

  WallpaperService { id: wallpaperSvc }

  AppLauncherService { id: appLauncherSvc }

  ModeService { id: modeSvc }

  AskpassService { id: askpassSvc }

  Shortcut {
    sequences: ["Alt+F5"]
    onActivated: { modeSvc.cycleMode(); clockItem.showModeIndicator(); }
    context: Qt.ApplicationShortcut
  }

  ControlCenter {
    isOpen: isControlCenterOpen
    modeSvc: modeSvc
    storedNotifications: notifService.storedNotifications
    doNotDisturb: notifService.doNotDisturb
    onDndToggled: (val) => notifService.doNotDisturb = val
    onDismissNotif: (notifRef) => notifService.dismissNotif(notifRef)
    onClearNotifs: notifService.clearAll()
    onCloseRequested: isControlCenterOpen = false
  }
}
